services:
  django:
    build:
      context: .
      target: django
  webserver:
    build:
      context: .
      target: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
