name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/django.yml

  sca:
    permissions:
      security-events: write
    uses: ./.github/workflows/sca.yml

  sast:
    permissions:
      security-events: write
    uses: ./.github/workflows/sast.yml

  deploy:
    needs:
      - test
      - sca
      - sast
    uses: ./.github/workflows/aws.yml
