name: Static Application Security Testing

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: requirements-sast.txt

      - name: Install Bandit
        run: pip install -r requirements-sast.txt

      - name: Bandit
        run: bandit --recursive --format sarif --output bandit.sarif .

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bandit.sarif
